# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2135bed2d4c5b06492825595a182c77fdfdf4bd5d602c40b6ca10f5d7716160d464f90c365b34eb482ada33419545db385233fc22670ce7775f012507bd871f8

test:
  secret_key_base: 034340abde97f8b1487e16eb3fae3cacf7630543c3c288ba9ef0daff50d2bb9ad5b60b71671aab17b9a6c63ce8e9b3bc3be1a31713a4a615c56c6af2a1458176

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
